version: 0.0
os: linux
files:
  - source: /build/libs/qamservices.war
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /scripts/configure_http_port.xsl
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
      runas: root      
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300 
      runas: root      
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application
      timeout: 300  
      runas: root